name: "Has installed dependencies"
description: "Action to check if dependencies have been installed according to the package manager used."
author: Hoverkraft
branding:
  icon: settings
  color: gray-dark

inputs:
  dependencies:
    description: "The dependencies to check."
    required: true

outputs:
  installed-dependencies:
    description: "A map of dependencies and the status weither they have been installed or not."
    value: ${{ steps.has-dependencies.outputs.installed-dependencies }}

runs:
  using: "composite"
  steps:
    - shell: bash
      # FIXME: workaround until will be merged: https://github.com/actions/runner/pull/1684
      run: mkdir -p ./self-actions/ && cp -r $GITHUB_ACTION_PATH/../* ./self-actions/

    - id: get-package-manager
      if: inputs.package-manager == ''
      uses: ./self-actions/get-package-manager

    - shell: bash
      # FIXME: workaround until will be merged: https://github.com/actions/runner/pull/1684
      run: |
        rm -fr ./self-actions

    - id: has-dependencies
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const dependenciesPatterns = {
            storybook: /@storybook\/[-a-z]+/,
            nx: /@nx\/[-a-z]+/,
          };

          const dependencies = `${{ inputs.dependencies }}`.split('\n').map(x => x.trim()).filter(x => x !== '');

          const hasDependencies = Object.fromEntries(dependencies.map(dependency => [dependency, false]));

          const setHasDependencies = (dependency) => {
            for (const dependencyName of Object.keys(hasDependencies)) {
              if (hasDependencies[dependencyName]) {
                continue;
              }

              if (dependencyName === dependency) {
                hasDependencies[dependencyName] = true;
                continue;
              }

              if (dependenciesPatterns[dependencyName] && dependenciesPatterns[dependencyName].test(dependency)) {
                hasDependencies[dependencyName] = true;
                continue;
              }
            }
          };

          const parseNpmDependencies = (dependencies) => {
            for (const dependencyName of Object.keys(dependencies)) {
              const dependency = dependencies[dependencyName];
              setHasDependencies(dependencyName);

              if (Object.values(hasDependencies).every(Boolean)) {
                break;
              }

              if (dependency.dependencies) {
                parseNpmDependencies(dependency.dependencies);
              }
            }
          };

          const parseYarnDependencies = (dependencies) => {
            for (const dependency of dependencies.data.trees) {

              const dependencyName = dependency.name.split('@').slice(0, -1).join('@');
              setHasDependencies(dependencyName);

              if (Object.values(hasDependencies).every(Boolean)) {
                break;
              }
            }
          };

          const parseDependencies = async () => {
            const { stdout } = await exec.getExecOutput(
              `${{ steps.get-package-manager.outputs.package-manager }} list --depth=1 --json --no-progress --pattern="${dependencies.join('|')}" --non-interactive`
            );

            const allInstalledDependencies = JSON.parse(stdout);

            switch (`${{ steps.get-package-manager.outputs.package-manager }}`) {
              case 'npm':
                parseNpmDependencies(allInstalledDependencies.dependencies);
                break;

              case 'yarn':
                parseYarnDependencies(allInstalledDependencies);
                break;
            }
          };

          await parseDependencies();

          core.setOutput('installed-dependencies', hasDependencies);
