name: "Lint"
description: "Action to lint Node.js projects with support for pull request reporting and annotations"
author: hoverkraft
branding:
  icon: check-circle
  color: blue

inputs:
  working-directory:
    description: |
      Working directory where lint commands are executed.
      Can be absolute or relative to the repository root.
    required: false
    default: "."
  container:
    description: "Whether running in container mode (skips checkout and node setup)"
    required: false
    default: "false"
  report-file:
    description: |
      Path to lint report file to process as GitHub annotations.
      Supports ESLint JSON and Checkstyle XML formats.
      If not specified, auto-detection will be attempted for common paths:
      - eslint-report.json, eslint.json
      - checkstyle-result.xml, checkstyle.xml
    required: false
    default: ""
  report-format:
    description: |
      Format of the lint report file. Supported values:
      - "eslint": ESLint JSON format
      - "checkstyle": Checkstyle XML format
      - "": Auto-detect from file extension
    required: false
    default: ""
  fail-on-error:
    description: "Whether to fail the action if linting errors are found"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - shell: bash
      # FIXME: workaround until will be merged: https://github.com/actions/runner/pull/1684
      run: mkdir -p ./self-lint-action/ && cp -r $GITHUB_ACTION_PATH/../* ./self-lint-action/

    - id: setup-node
      if: inputs.container != 'true'
      uses: ./self-lint-action/setup-node
      with:
        working-directory: ${{ inputs.working-directory }}
        dependencies-cache: |
          nx
          prettier

    - id: get-package-manager
      if: inputs.container == 'true'
      uses: ./self-lint-action/get-package-manager
      with:
        working-directory: ${{ inputs.working-directory }}

    # jscpd:ignore-start
    - id: run-lint
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      env:
        RUN_SCRIPT_COMMAND: ${{ inputs.container == 'true' && steps.get-package-manager.outputs.run-script-command || steps.setup-node.outputs.run-script-command }}
        WORKING_DIRECTORY: ${{ inputs.working-directory }}
        FAIL_ON_ERROR: ${{ inputs.fail-on-error }}
      with:
        script: |
          const path = require('node:path');
          const exec = require('@actions/exec');

          const workingDirectory = process.env.WORKING_DIRECTORY || '.';
          const runScriptCommand = process.env.RUN_SCRIPT_COMMAND;
          const failOnError = process.env.FAIL_ON_ERROR === 'true';

          core.info('👕 Running lint...');

          try {
            const result = await exec.getExecOutput(runScriptCommand, ['lint'], {
              cwd: path.resolve(process.env.GITHUB_WORKSPACE, workingDirectory),
              ignoreReturnCode: true
            });
            
            if (result.stdout) core.info(result.stdout);
            if (result.stderr) core.warning(result.stderr);
            
            core.setOutput('lint-exit-code', result.exitCode);
            
            if (result.exitCode !== 0 && failOnError) {
              core.setFailed(`Linting failed with exit code ${result.exitCode}`);
            } else if (result.exitCode !== 0) {
              core.warning(`Linting failed with exit code ${result.exitCode}`);
            }
          } catch (error) {
            core.setOutput('lint-exit-code', 1);
            core.setFailed(`Linting error: ${error.message}`);
          }
    # jscpd:ignore-end
    # Auto-detect report file if not specified
    - id: detect-report-file
      if: always() && inputs.report-file == ''
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      env:
        WORKING_DIRECTORY: ${{ inputs.working-directory }}
      with:
        script: |
          const fs = require('node:fs');
          const path = require('node:path');

          const workingDirectory = process.env.WORKING_DIRECTORY || '.';
          const workDir = path.resolve(process.env.GITHUB_WORKSPACE, workingDirectory);

          // Common lint report file paths
          const commonPaths = [
            'eslint-report.json',
            'eslint.json',
            '.eslint-report.json',
            'checkstyle-result.xml',
            'checkstyle.xml',
            'lint-results.xml',
            'reports/eslint-report.json',
            'reports/checkstyle.xml'
          ];

          for (const filePath of commonPaths) {
            const fullPath = path.join(workDir, filePath);
            if (fs.existsSync(fullPath)) {
              core.info(`Auto-detected lint report file: ${filePath}`);
              core.setOutput('report-file', filePath);
              
              // Auto-detect format from extension
              if (filePath.endsWith('.json')) {
                core.setOutput('report-format', 'eslint');
              } else if (filePath.endsWith('.xml')) {
                core.setOutput('report-format', 'checkstyle');
              }
              return;
            }
          }

          core.info('No lint report file auto-detected');
          core.setOutput('report-file', '');
          core.setOutput('report-format', '');

    # Process ESLint report
    - name: 📊 Annotate ESLint results
      if: always() && (inputs.report-file != '' || steps.detect-report-file.outputs.report-file != '') && (inputs.report-format == 'eslint' || steps.detect-report-file.outputs.report-format == 'eslint' || (inputs.report-format == '' && steps.detect-report-file.outputs.report-format == ''))
      uses: ataylorme/eslint-annotate-action@d57a1193d4c59cbfbf2f1529e82e2f8e0da1498d # v3.0.0
      with:
        report-json: ${{ inputs.working-directory }}/${{ inputs.report-file != '' && inputs.report-file || steps.detect-report-file.outputs.report-file }}
        fail-on-error: false
        fail-on-warning: false

    # Process Checkstyle report
    - name: 📊 Annotate Checkstyle results
      if: always() && (inputs.report-file != '' || steps.detect-report-file.outputs.report-file != '') && (inputs.report-format == 'checkstyle' || steps.detect-report-file.outputs.report-format == 'checkstyle')
      uses: lcollins/checkstyle-github-action@8e0abb97e71a72c2cf9d6f0619e38002cb6e36c9 # v2.0.0
      with:
        path: ${{ inputs.working-directory }}/${{ inputs.report-file != '' && inputs.report-file || steps.detect-report-file.outputs.report-file }}

    - shell: bash
      if: always() && steps.run-lint.outputs.lint-exit-code != '0' && inputs.fail-on-error == 'true'
      run: |
        echo "::error::Linting failed. Please fix the errors above."
        exit 1

    # FIXME: workaround until will be merged: https://github.com/actions/runner/pull/1684
    - shell: bash
      if: always()
      run: rm -fr ./self-lint-action
