name: "Lint"
description: "Action to lint Node.js projects with support for pull request reporting and annotations"
author: hoverkraft
branding:
  icon: check-circle
  color: blue

inputs:
  working-directory:
    description: |
      Working directory where lint commands are executed.
      Can be absolute or relative to the repository root.
    required: false
    default: "."
  container:
    description: "Whether running in container mode (skips checkout and node setup)"
    required: false
    default: "false"
  report-file:
    description: |
      Path to lint report file to process as GitHub annotations.
      Supports ESLint JSON and Checkstyle XML formats.
      If not specified, no report processing is done.
    required: false
    default: ""
  report-format:
    description: |
      Format of the lint report file. Supported values:
      - "eslint": ESLint JSON format
      - "checkstyle": Checkstyle XML format
      - "": Auto-detect from file extension
    required: false
    default: ""
  fail-on-error:
    description: "Whether to fail the action if linting errors are found"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - shell: bash
      # FIXME: workaround until will be merged: https://github.com/actions/runner/pull/1684
      run: mkdir -p ./self-lint-action/ && cp -r $GITHUB_ACTION_PATH/../* ./self-lint-action/

    - id: setup-node
      if: inputs.container != 'true'
      uses: ./self-lint-action/setup-node
      with:
        working-directory: ${{ inputs.working-directory }}
        dependencies-cache: |
          nx
          prettier

    - id: get-package-manager
      if: inputs.container == 'true'
      uses: ./self-lint-action/get-package-manager
      with:
        working-directory: ${{ inputs.working-directory }}

    # jscpd:ignore-start
    - id: run-lint
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      env:
        RUN_SCRIPT_COMMAND: ${{ inputs.container == 'true' && steps.get-package-manager.outputs.run-script-command || steps.setup-node.outputs.run-script-command }}
        WORKING_DIRECTORY: ${{ inputs.working-directory }}
        FAIL_ON_ERROR: ${{ inputs.fail-on-error }}
      with:
        script: |
          const { exec } = require('child_process');
          const { promisify } = require('util');
          const execAsync = promisify(exec);
          const path = require('path');

          const workingDirectory = process.env.WORKING_DIRECTORY || '.';
          const runScriptCommand = process.env.RUN_SCRIPT_COMMAND;
          const failOnError = process.env.FAIL_ON_ERROR === 'true';

          core.info('👕 Running lint...');

          try {
            const { stdout, stderr } = await execAsync(`${runScriptCommand} lint`, {
              cwd: path.resolve(process.env.GITHUB_WORKSPACE, workingDirectory)
            });
            
            if (stdout) core.info(stdout);
            if (stderr) core.warning(stderr);
            
            core.setOutput('lint-exit-code', 0);
          } catch (error) {
            core.setOutput('lint-exit-code', error.code || 1);
            
            if (error.stdout) core.info(error.stdout);
            if (error.stderr) core.error(error.stderr);
            
            if (failOnError) {
              core.setFailed(`Linting failed with exit code ${error.code || 1}`);
            } else {
              core.warning(`Linting failed with exit code ${error.code || 1}`);
            }
          }
    # jscpd:ignore-end
    # Process ESLint report
    - name: 📊 Annotate ESLint results
      if: always() && inputs.report-file != '' && (inputs.report-format == 'eslint' || inputs.report-format == '')
      uses: ataylorme/eslint-annotate-action@d57a1193d4c59cbfbf2f1529e82e2f8e0da1498d # v3.0.0
      with:
        report-json: ${{ inputs.working-directory }}/${{ inputs.report-file }}
        fail-on-error: false
        fail-on-warning: false

    # Process Checkstyle report
    - name: 📊 Annotate Checkstyle results
      if: always() && inputs.report-file != '' && inputs.report-format == 'checkstyle'
      uses: lcollins/checkstyle-github-action@8e0abb97e71a72c2cf9d6f0619e38002cb6e36c9 # v2.0.0
      with:
        path: ${{ inputs.working-directory }}/${{ inputs.report-file }}

    - shell: bash
      if: always() && steps.run-lint.outputs.lint-exit-code != '0' && inputs.fail-on-error == 'true'
      run: |
        echo "::error::Linting failed. Please fix the errors above."
        exit 1

    # FIXME: workaround until will be merged: https://github.com/actions/runner/pull/1684
    - shell: bash
      if: always()
      run: rm -fr ./self-lint-action
