name: "Setup Node.js"
description: "Action to setup Node.js and install dependencies according to the package manager used."
author: Hoverkraft
branding:
  icon: settings
  color: gray-dark

inputs:
  dependencies-cache:
    description: "List of dependencies for which the cache should be managed"
    required: false
    default: ""

outputs:
  run-script-command:
    description: "The command to run a script in the package.json file"
    value: ${{ steps.get-package-manager.outputs.run-script-command }}
runs:
  using: "composite"
  steps:
    - shell: bash
      # FIXME: workaround until will be merged: https://github.com/actions/runner/pull/1684
      run: mkdir -p ./self-setup-node-action/ && cp -r $GITHUB_ACTION_PATH/../* ./self-setup-node-action/

    - id: get-package-manager
      if: inputs.package-manager == ''
      uses: ./self-setup-node-action/get-package-manager

    - id: get-node-version-file
      shell: bash
      run: |
        # Node version file
        if [ -f ".nvmrc" ]; then
          echo "node-version-file=.nvmrc" >> $GITHUB_OUTPUT
          exit 0
        fi
        if [ -f ".node-version" ]; then
          echo "node-version-file=.node-version" >> $GITHUB_OUTPUT
          exit 0
        fi

    - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        node-version-file: ${{ steps.get-node-version-file.outputs.node-version-file }}
        cache: ${{ steps.get-package-manager.outputs.package-manager }}
        cache-dependency-path: ${{ steps.get-package-manager.outputs.cache-dependency-path }}

    - shell: bash
      run: ${{ steps.get-package-manager.outputs.install-command }}

    - if: inputs.dependencies-cache != ''
      uses: ./self-setup-node-action/dependencies-cache
      with:
        dependencies: ${{ inputs.dependencies-cache }}

    # FIXME: workaround until will be merged: https://github.com/actions/runner/pull/1684
    - shell: bash
      if: always()
      run: |
        rm -fr ./self-setup-node-action
