name: "Dependencies cache"
description: "Action to setup dependencies cache managment."
author: Hoverkraft
branding:
  icon: archive
  color: gray-dark

inputs:
  dependencies:
    description: "List of dependencies for which the cache should be managed."
    required: true
  working-directory:
    description: "Working directory where the dependencies are installed."
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - shell: bash
      # FIXME: workaround until will be merged: https://github.com/actions/runner/pull/1684
      run: mkdir -p ./self-dependencies-cache-action/ && cp -r $GITHUB_ACTION_PATH/../* ./self-dependencies-cache-action/

    - id: has-installed-dependencies
      if: inputs.dependencies != ''
      uses: ./self-dependencies-cache-action/has-installed-dependencies
      with:
        dependencies: ${{ inputs.dependencies }}
        working-directory: ${{ inputs.working-directory }}

    - id: get-package-manager
      if: inputs.package-manager == ''
      uses: ./self-dependencies-cache-action/get-package-manager
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: ♻️ NX cache
      if: fromJson(steps.has-installed-dependencies.outputs.installed-dependencies).nx == true
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ${{ inputs.working-directory }}/node_modules/.cache/nx
        key: ${{ runner.os }}-cache-nx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-cache-nx-

    - name: ♻️ Prettier cache
      if: fromJson(steps.has-installed-dependencies.outputs.installed-dependencies).prettier == true
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ${{ inputs.working-directory }}/node_modules/.cache/prettier
        key: ${{ runner.os }}-cache-prettier-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-cache-prettier-

    - name: ♻️ Gatsby cache
      if: fromJson(steps.has-installed-dependencies.outputs.installed-dependencies).gatsby == true
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          ${{ inputs.working-directory }}/.cache
          ${{ inputs.working-directory }}/public
        key: ${{ runner.os }}-cache-gatsby-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-cache-gatsby-

    - name: ♻️ Storybook cache
      if: fromJson(steps.has-installed-dependencies.outputs.installed-dependencies).storybook == true
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ${{ inputs.working-directory }}/node_modules/.cache/storybook
        key: ${{ runner.os }}-cache-storybook-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-cache-storybook-

    - name: ♻️ Get Jest cache dir
      id: jest-cache-dir-path
      if: fromJson(steps.has-installed-dependencies.outputs.installed-dependencies).jest == true
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        case "${{ steps.get-package-manager.outputs.package-manager }}" in
          npm)
            JEST_CONFIG=$(${{ steps.get-package-manager.outputs.package-manager }} exec jest -- --showConfig)
            ;;
          *)
            JEST_CONFIG=$(${{ steps.get-package-manager.outputs.package-manager }} jest --showConfig)
            ;;
        esac

        if [ -z "$JEST_CONFIG" ]; then
          echo "::error::Unable to get Jest config"
          exit 1
        fi

        echo "::debug::Jest config: $JEST_CONFIG"

        JEST_CACHE_DIR=$(echo "$JEST_CONFIG" | grep -oP '(?<="cacheDirectory": ")[^"]+(?=")')

        if [ -z "$JEST_CACHE_DIR" ]; then
          echo "::error ::Unable to get Jest cache directory from config: $JEST_CONFIG"
          exit 1
        fi

        echo "::debug::Jest cache directory: $JEST_CACHE_DIR"

        echo "dir=$JEST_CACHE_DIR" >> "$GITHUB_OUTPUT"

    - name: ♻️ Test cache
      if: steps.jest-cache-dir-path.outputs.dir
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ${{ steps.jest-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-test-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-test-

    # FIXME: workaround until will be merged: https://github.com/actions/runner/pull/1684
    - shell: bash
      if: always()
      run: |
        rm -fr ./self-dependencies-cache-action
