name: Internal - Main - Continuous Integration

on:
  push:
    branches: [main]
    tags: ["*"]

  workflow_dispatch:

  schedule:
    - cron: "25 8 * * 1"

permissions:
  actions: write
  contents: write
  pages: write
  pull-requests: write
  security-events: write
  statuses: write
  # FIXME: This is a workaround for having workflow ref. See https://github.com/orgs/community/discussions/38659
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/__shared-ci.yml
    secrets: inherit

  release:
    needs: ci
    if: github.event_name != 'schedule'
    uses: hoverkraft-tech/ci-github-publish/.github/workflows/release-actions.yml@6d9e5d48da1a80c085e8ed867d680a5e99b28217 # 0.8.0
    with:
      update-all: ${{ (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) || github.event_name == 'workflow_dispatch' }}
      github-app-id: ${{ vars.CI_BOT_APP_ID }}
    secrets:
      github-app-key: ${{ secrets.CI_BOT_APP_PRIVATE_KEY }}
