name: Internal - Tests for "dependencies-cache" action

on:
  workflow_call:

permissions: {}

jobs:
  test:
    name: Test "dependencies-cache" (${{ matrix.working-directory }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - working-directory: tests/npm
            package-manager: npm

          - working-directory: tests/pnpm
            package-manager: pnpm

          - working-directory: tests/pnpm-package-manager
            package-manager: pnpm

          - working-directory: tests/yarn
            package-manager: yarn
    steps:
      # jscpd:ignore-start

      - name: Arrange - Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Arrange - Setup Node.js runtime
        id: arrange-setup-node
        uses: ./actions/setup-node
        with:
          working-directory: ${{ matrix.working-directory }}

      - name: Arrange - Verify expected package manager
        id: arrange-check-package-manager
        run: |
          if [[ "${{ steps.arrange-setup-node.outputs.run-script-command }}" != "${{ matrix.package-manager }}"* ]]; then
            echo "Package manager is not ${{ matrix.package-manager }}"
            exit 1
          fi

      # jscpd:ignore-end

      - name: Act - Run "dependencies-cache" action
        id: act-get-dependencies-cache
        uses: ./actions/dependencies-cache
        with:
          working-directory: ${{ matrix.working-directory }}
          dependencies: |
            gatsby
            jest
            nx
            prettier
            storybook
            unknown

      - name: Assert - Check "dependencies-cache" configured cache
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const assert = require("assert");
