name: Internal - Tests for "dependencies-cache" action

on:
  workflow_call:

permissions: {}

jobs:
  test:
    name: Test "dependencies-cache" (${{ matrix.working-directory }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - working-directory: tests/npm
            package-manager: npm

          - working-directory: tests/pnpm
            package-manager: pnpm

          - working-directory: tests/pnpm-package-manager
            package-manager: pnpm

          - working-directory: tests/yarn
            package-manager: yarn
    steps:
      # jscpd:ignore-start

      - name: Arrange - Checkout sources
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Arrange - Setup Node.js runtime
        id: arrange-setup-node
        uses: ./actions/setup-node
        with:
          working-directory: ${{ matrix.working-directory }}

      - name: Arrange - Verify expected package manager
        id: arrange-check-package-manager
        env:
          ACTUAL_RUN_SCRIPT_COMMAND: ${{ steps.arrange-setup-node.outputs.run-script-command }}
          EXPECTED_PACKAGE_MANAGER: ${{ matrix.package-manager }}
        run: |
          if [[ "$ACTUAL_RUN_SCRIPT_COMMAND" != "$EXPECTED_PACKAGE_MANAGER"* ]]; then
            echo "Package manager is not $EXPECTED_PACKAGE_MANAGER"
            exit 1
          fi

      # jscpd:ignore-end

      - name: Act - Run "dependencies-cache" action
        id: act-get-dependencies-cache
        uses: ./actions/dependencies-cache
        with:
          working-directory: ${{ matrix.working-directory }}
          dependencies: |
            gatsby
            jest
            nx
            prettier
            storybook
            unknown

      - name: Assert - Check "dependencies-cache" configured cache
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const assert = require("assert");
